import Head from "next/head";
// import Image from "next/image";
import { AddPost, Footer, Form, Navbar } from "../components";
// import { Inter } from "@next/font/google";
import dynamic from "next/dynamic";

const RecordView = dynamic(() => import("../components/Record"));

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>ForHer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="min-h-screen bg-black w-full overflow-x-hidden">
        {/* <div className="w-full overflow-hidden absolute h-full top-0">
          <img
            src="/sheBuilds.png"
            className="w-screen h-full overflow-hidden object-fill"
          />
        </div> */}
        <div className="mt-10 z-[1000]">
          {/* <AddPost /> */}
          {/* <div className=""> */}
          {/* <Form /> */}
          <div className="text-white">
            <div className="mx-auto w-fit p-3 underline">RECORD SECTION</div>
            <p className="w-fit mx-auto">
              Media is Automatically Uploaded when recorded. This is to help you
              out in emergency situations. Other than that one may just upload
              files.
            </p>
            <div className="mx-auto w-fit">
              <p className="mx-auto w-fit">Audio</p>
              <RecordView id="audio" audio={true} />
            </div>
            <div>
              <p className="mx-auto w-fit">Video</p>              
              <RecordView video={true} />
            </div>
            <div>
              <p className="mx-auto w-fit">Screen Record</p>
              
              <RecordView screen={true} />
            </div>
          </div>
          {/* </div> */}
        </div>
      </div>
    </>
  );
}
